# PPI-Cancer-Prediction Notebook

In [25]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 1. Data Exploration
### 1.1 Protein Aliases Dataset

In [12]:
df1 = pd.read_csv("C:\Local Programming Projects\ppi-cancer-prediction\data\9606.protein.aliases.v12.0.txt", sep='\t')
df1.head()

     #string_protein_id alias                  source
0  9606.ENSP00000000233  2B6H             Ensembl_PDB
1  9606.ENSP00000000233  2B6H          UniProt_DR_PDB
2  9606.ENSP00000000233   381  Ensembl_HGNC_entrez_id
3  9606.ENSP00000000233   381             KEGG_GENEID
4  9606.ENSP00000000233   381       KEGG_KEGGID_SHORT

In [17]:
print("Shape of dataset: ", df1.shape)
print("Column labels: ", df1.columns)
df1.info()
df1.describe()

Shape of dataset:  (3889207, 3)
Column labels:  Index(['#string_protein_id', 'alias', 'source'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 3889207 entries, 0 to 3889206
Data columns (total 3 columns):
 #   Column              Dtype
---  ------              -----
 0   #string_protein_id  str
 1   alias               str
 2   source              str
dtypes: str(3)
memory usage: 89.0 MB

          #string_protein_id         alias        source
count                3889207       3889201       3889207
unique                 19699       2553437            90
top     9606.ENSP00000354728  R-HSA-162582  Ensembl_EMBL
freq                   92796          5472        487265

In [19]:
df1['#string_protein_id'].value_counts()

#string_protein_id
9606.ENSP00000354728    92796
9606.ENSP00000354982    78720
9606.ENSP00000355046    65409
9606.ENSP00000355265    54408
9606.ENSP00000354665    53281
                        ...
9606.ENSP00000482263        9
9606.ENSP00000482855        8
9606.ENSP00000484918        8
9606.ENSP00000501013        8
9606.ENSP00000501098        8
Name: count, Length: 19699, dtype: int64

In [21]:
df1.isnull().sum().sort_values(ascending=False)

alias                 6
#string_protein_id    0
source                0
dtype: int64

### 1.2 Protein Links Dataset

In [28]:
df2 = pd.read_csv("C:\Local Programming Projects\ppi-cancer-prediction\data\9606.protein.links.v12.0.txt.gz")
df2.head()

                protein1 protein2 combined_score
0  9606.ENSP00000000233 9606.ENSP00000356607 173
1  9606.ENSP00000000233 9606.ENSP00000427567 154
2  9606.ENSP00000000233 9606.ENSP00000253413 151
3  9606.ENSP00000000233 9606.ENSP00000493357 471
4  9606.ENSP00000000233 9606.ENSP00000324127 201

In [34]:
print("Shape of dataset: ", df2.shape)
print("Column labels: ", df2.columns)
df2.info()
df2.describe()

Shape of dataset:  (13715404, 1)
Column labels:  Index(['protein1 protein2 combined_score'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 13715404 entries, 0 to 13715403
Data columns (total 1 columns):
 #   Column                            Dtype
---  ------                            -----
 0   protein1 protein2 combined_score  str
dtypes: str(1)
memory usage: 104.6 MB

                     protein1 protein2 combined_score
count                                        13715404
unique                                       13715404
top     9606.ENSP00000000233 9606.ENSP00000356607 173
freq                                                1

In [35]:
df2.isnull().sum().sort_values(ascending=False)

protein1 protein2 combined_score    0
dtype: int64

### 1.3 Cosmic Cancer Gene Census Dataset

In [48]:
df3 = pd.read_csv("C:\Local Programming Projects\ppi-cancer-prediction\data\Cosmic_CancerGeneCensus_v103_GRCh37.tsv", sep='\t')
df3.head(5)

,GENE_SYMBOL,NAME,COSMIC_GENE_ID,CHROMOSOME,GENOME_START,GENOME_STOP,CHR_BAND,SOMATIC,GERMLINE,TUMOUR_TYPES_SOMATIC,...,CANCER_SYNDROME,TISSUE_TYPE,MOLECULAR_GENETICS,ROLE_IN_CANCER,MUTATION_TYPES,TRANSLOCATION_PARTNER,OTHER_GERMLINE_MUT,OTHER_SYNDROME,TIER,SYNONYMS
0,A1CF,APOBEC1 complementation factor,COSG46891,10,52559169.0,52645435.0,10q11.23,y,n,melanoma,...,NaN,E,NaN,oncogene,Mis,NaN,n,NaN,2,"A1CF,ENSG00000148584.10,Q9NQ94,29974,ACF,ACF64..."
1,ABI1,abl interactor 1,COSG5120,10,27035522.0,27150016.0,10p12.1,y,n,AML,...,NaN,L,Dom,"TSG, fusion",T,KMT2A,n,NaN,1,"ABI1,ENSG00000136754.12,Q8IZP0,10006,ABI-1,E3B1"
2,ABL1,"ABL proto-oncogene 1, non-receptor tyrosine ki...",COSG4968,9,133589333.0,133763062.0,9q34.12,y,n,"CML, ALL, T-ALL",...,NaN,L,Dom,"oncogene, fusion","T, Mis","BCR, ETV6, NUP214",n,NaN,1,"ABL1,ENSG00000097007.13,P00519,25,JTK7,c-ABL,p150"
3,ABL2,"ABL proto-oncogene 2, non-receptor tyrosine ki...",COSG36573,1,179068462.0,179198819.0,1q25.2,y,n,AML,...,NaN,L,Dom,"oncogene, fusion",T,ETV6,n,NaN,1,"ABL2,ENSG00000143322.15,P42684,27,ARG"
4,ACKR3,atypical chemokine receptor 3,COSG38910,2,237476430.0,237491001.0,2q37.3,y,n,lipoma,...,NaN,M,Dom,"oncogene, fusion",T,HMGA2,n,NaN,1,"ACKR3,ENSG00000144476.5,P25106,57007,GPR159,RDC1"

In [40]:
print("Shape of dataset: ", df3.shape)
print("Column labels: ", df3.columns)
df3.info()
df3.describe()

Shape of dataset:  (763, 21)
Column labels:  Index(['GENE_SYMBOL', 'NAME', 'COSMIC_GENE_ID', 'CHROMOSOME', 'GENOME_START',
       'GENOME_STOP', 'CHR_BAND', 'SOMATIC', 'GERMLINE',
       'TUMOUR_TYPES_SOMATIC', 'TUMOUR_TYPES_GERMLINE', 'CANCER_SYNDROME',
       'TISSUE_TYPE', 'MOLECULAR_GENETICS', 'ROLE_IN_CANCER', 'MUTATION_TYPES',
       'TRANSLOCATION_PARTNER', 'OTHER_GERMLINE_MUT', 'OTHER_SYNDROME', 'TIER',
       'SYNONYMS'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 763 entries, 0 to 762
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENE_SYMBOL            763 non-null    str
 1   NAME                   763 non-null    str
 2   COSMIC_GENE_ID         763 non-null    str
 3   CHROMOSOME             763 non-null    str
 4   GENOME_START           757 non-null    float64
 5   GENOME_STOP            757 non-null    float64
 6   CHR_BAND               763 non-null    str
 7   SOMATIC                763 non-null    str
 8   GERMLINE               763 non-null    str
 9   TUMOUR_TYPES_SOMATIC   719 non-null    str
 10  TUMOUR_TYPES_GERMLINE  108 non-null    str
 11  CANCER_SYNDROME        91 non-null     str
 12  TISSUE_TYPE            763 non-null    str
 13  MOLECULAR_GENETICS     593 non-null    str
 14  ROLE_IN_CANCER         718 non-null    str
 15  MUTATION_TYPES         762 non-null    str
 16  TRANSLOCATION_PARTNER  371 non-null    str
 17  OTHER_GERMLINE_MUT     763 non-null    str
 18  OTHER_SYNDROME         93 non-null     str
 19  TIER                   763 non-null    int64
 20  SYNONYMS               763 non-null    str
dtypes: float64(2), int64(1), str(18)
memory usage: 125.3 KB

       GENOME_START   GENOME_STOP        TIER
count  7.570000e+02  7.570000e+02  763.000000
mean   7.483567e+07  7.496238e+07    1.226737
std    5.512818e+07  5.514190e+07    0.418995
min    2.183560e+05  2.568150e+05    1.000000
25%    3.328634e+07  3.329705e+07    1.000000
50%    5.721082e+07  5.742934e+07    1.000000
75%    1.139303e+08  1.141214e+08    1.000000
max    2.436515e+08  2.440144e+08    2.000000

In [41]:
df3.isnull().sum().sort_values(ascending=False)

CANCER_SYNDROME          672
OTHER_SYNDROME           670
TUMOUR_TYPES_GERMLINE    655
TRANSLOCATION_PARTNER    392
MOLECULAR_GENETICS       170
ROLE_IN_CANCER            45
TUMOUR_TYPES_SOMATIC      44
GENOME_START               6
GENOME_STOP                6
MUTATION_TYPES             1
COSMIC_GENE_ID             0
NAME                       0
GENE_SYMBOL                0
CHROMOSOME                 0
CHR_BAND                   0
SOMATIC                    0
GERMLINE                   0
TISSUE_TYPE                0
OTHER_GERMLINE_MUT         0
TIER                       0
SYNONYMS                   0
dtype: int64

In [47]:
df3['TUMOUR_TYPES_SOMATIC'].value_counts().head()

TUMOUR_TYPES_SOMATIC
AML         39
T-ALL       19
prostate    14
ALL         12
melanoma    11
Name: count, dtype: int64

## Data Preparation